name: Deploy API

on:
  push: 
    branches:
      - main
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: yarn install --frozen-lock-file 
    - name: Build API
      run: yarn build --filter=api
    - name: Bundle the build
      run: |
        mkdir ../build
        cp -R apps/api/dist ../build
        tar -cvf deploy.tar ../build/
    - name: Copy to server
      uses: appleboy/scp-action@master
      with: 
        host: ${{ secrets.API_HOST }}
        username: ${{ secrets.API_USERNAME }}
        port: ${{ secrets.API_PORT }}
        password: ${{ secrets.API_PASSWORD }}
        source: deploy.tar
        target: /tmp/
        