---
name: Deploy API
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bundle the build
        run: |
          mkdir ../build
          cp -R apps/api ../build
          cd ../build
          touch deploy.tar.gz
          echo "Bundling spi repo"
          tar -C api -czf deploy.tar.gz .
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
          touch ~/.ssh/id_key
          echo "${{ secrets.SSH }}" >> ~/.ssh/id_key
          chmod 400 ~/.ssh/id_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_key
          ssh-keyscan -t ed25519 ${{ secrets.API_HOST }}  >> ~/.ssh/known_hosts
          scp deploy.tar.gz ${{ secrets.API_USERNAME }}@${{ secrets.API_HOST }}:/tmp
          ssh aumni@${{ secrets.API_HOST }} '

            echo making deployment $(echo "${{ github.sha }}" | cut -c1-8)
            mkdir -p /var/www/api.gaspmoviereview.com/deployments/$(echo "${{ github.sha }}" | cut -c1-8)
            mv /tmp/deploy.tar.gz /var/www/api.gaspmoviereview.com/deployments/$(echo "${{ github.sha }}" | cut -c1-8)
            cd /var/www/api.gaspmoviereview.com/deployments/$(echo "${{ github.sha }}" | cut -c1-8)
            echo "Extracting tarball"
            tar -xzf deploy.tar.gz
            rm -rf deploy.tar.gz
            yarn install --frozen-lockfile
            yarn build
            cp ../.env ./.env
            
            echo "Exiting server"
            exit

          '
          echo "Removing key"
          rm -rf ~/.ssh/id_key
